### ISSUE TITLE
incorrect path

### ISSUE THREAD

**Issue by vjd** [dpastoor/overseer#4]
after updating to commit https://github.com/dpastoor/overseer/commit/4f11e0b484462c82558603114f95ec5c227fb425 there seems to be an error in finding the right path for the model file. 

The model directory and the cache location are set correctly but the `add_model_file` is not able locate the cpp file providing the following error -

```
> models <- source("../modeling/models.R")$value
model dir set to /Users/vijay/Repos/rbp/rbp7000/modeling
cache location set to /Users/vijay/Repos/rbp/rbp7000/modeling/.modelcache
path[1]="run18.cpp": No such file or directoryError in models$add_model_file("run18") : 
  model file not detected at: run18
```

**Comment by vjd** [comment]
I think, it is this specific [line](https://github.com/dpastoor/overseer/commit/83275a56eb0407886ceee1adf621c8ed2d33f376#diff-2adad79cd142135e65ebc64e86321b4bR85) that is causing the issue 

I jtried to emulate normalizepath on as it has to work and this is what I get -

```

> normalizePath(paste0("/Users/vijay/Repos/rbp/rbp7000/modeling",".cpp"))
[1] "/Users/vijay/Repos/persn/alnylam/fitusiran/modeling.cpp"
Warning message:
In normalizePath(paste0("/Users/vijay/Repos/rbp/rbp7000/modeling",  :
  path[1]="/Users/vijay/Repos/rbp/rbp7000/modeling.cpp": No such file or directory
```

reverted back to older commit https://github.com/dpastoor/overseer/commit/e1218ada54558c05ae0bf7e5b3a9de0a5139acd3which works fine!

**Comment by dpastoor** [comment]
What does your models. R file look like?

**Comment by vjd** [comment]
```
library(overseer)

# if run interactively setwd() to file location
# sourcing will keep everything relative to this file similar to knitting in Rmd

models <- Overseer$new()

# pull in model saved as run18.cpp
models$add_model_file("run18")


models

```

**Comment by dpastoor** [comment]
Hmm ok thanks - I'll track it down shortly

**Comment by dpastoor** [comment]
Fix is in 939136f857a04b5aec76d1cfa58bf0076ff61ac4 

thought I had caught all the areas that need to be appended to the model dir, needed to be referenced relative to the model_dir

**Comment by dpastoor** [comment]
bonked the adding from dir now though - hold off on updating

**Comment by dpastoor** [comment]
ok everything should work - put out a new release

**Comment by dpastoor** [comment]
release here 8abdf4ac2c8d99ccd627124cebf5948b2db9f066
