### ISSUE TITLE
installing overseer re-installs mrgsolve

### ISSUE THREAD

**Issue by vjd** [dpastoor/overseer#7]
devtools::install_github() of overseer re-install's mrgsolve from source. Is this intentional?

**Comment by kylebaron** [comment]
What version of `mrgsolve` are you using?  It seems like `install_github` has some functionality to compare version numbers for dependencies ... but not sure how this would play into what you are seeing.

**Comment by dpastoor** [comment]
This has nothing to do with overseer - this is the default behavior of devtools::install_github. You might just be noticing it since not many packages import mrgsolve. This is also not something specific to mrgsolve, any package that has compilation steps
